version: '3.3'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: eagle_nest
    networks:
      - mycodecamp
networks:
  mycodecamp:
