version: '3.3'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: easgle_nest
    networks:
      - mycodecamp
networks:
  mycodecamp:
